[package]
name = "plebiscite-types"

version.workspace = true
edition.workspace = true
authors.workspace = true


#[[lib]]
#path = "src/lib.rs"


[dependencies]
serde = { version = "1", features = [ "derive" ] }

